# Complete Python NumPy Tutorial (Creating Arrays, Indexing, Math, Statistics, Reshaping)

In [2]:
import numpy as np

## Basics

In [4]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [11]:
# Dimension
print(f"a dimensions: {a.ndim}")
print(f"b dimensions: {b.ndim}")

# Shape
print(f"a shape: {a.shape}")
print(f"b shape: {b.shape}")

a dimensions: 1
b dimensions: 2
a shape: (3,)
b shape: (2, 3)


In [17]:
# Type
print(a.dtype)
print(b.dtype)

int64
float64


In [21]:
# Size
print(a.itemsize)
print(b.itemsize)

c = np.array([1,2,3], dtype='int16')
print(c.itemsize)
print(c.size)

8
8
2
3


## Accessing/Changing specific elements, rows, columns, etc

In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a.shape)

(2, 7)


#### Get a specific element

In [38]:
a[1, 5]

13

In [39]:
# negative notation
a[1, -2]

13

#### Get a specific row

In [29]:
a[0, :]

[1 2 3 4 5 6 7]


#### Get a specific column

In [32]:
a[:, 2]

array([ 3, 10])

#### Getting a little more fancy [startindex:endindex:stepsize]

In [37]:
a[0, 1:6:2]

array([2, 4, 6])

In [40]:
### Changing values

In [43]:
a[1,5] = 20
print(a)

# change a whole column
a[:, 2] = 27
print(a)

[[ 1  2 27  4  5  6  7]
 [ 8  9 27 11 12 20 14]]
[[ 1  2 27  4  5  6  7]
 [ 8  9 27 11 12 20 14]]


### 3d Example

In [44]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Get specific element - work outside in

In [45]:
b[0,1,1]

4

### Initialize Arrays

In [51]:
a = np.zeros(5)
b = np.zeros((2,3))
print(a)
print(b)
c = np.ones(5, dtype='int16')
print(c)
d = np.full((2,2), 73)
print(d)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[1 1 1 1 1]
[[73 73]
 [73 73]]


#### Full Like

In [52]:
a = np.full((4,5), 37)
b = np.full_like(a, 73)
print(a)
print(b)

[[37 37 37 37 37]
 [37 37 37 37 37]
 [37 37 37 37 37]
 [37 37 37 37 37]]
[[73 73 73 73 73]
 [73 73 73 73 73]
 [73 73 73 73 73]
 [73 73 73 73 73]]


#### Random

In [56]:
np.random.randint(7, size=(4,2))

array([[0, 6],
       [0, 6],
       [1, 6],
       [6, 2]])

In [59]:
np.random.randint(1,11, size=(4,2))

array([[10,  6],
       [ 5, 10],
       [ 8,  8],
       [ 7,  6]])

### Careful when copying arrays

In [62]:
a = np.array([1,2,3])
b = a
b[0] = 0
print(a)

[0 2 3]


#### Use copy

In [64]:
a = np.array([1,2,3])
b = np.copy(a)
b[0] = 0
print(a)

[1 2 3]


## Mathematics

In [70]:
a = np.array([1,2,3])
print(a)
a += 2
print(a)
a = a ** 2
print(a)
a *= 2
print(a)

[1 2 3]
[3 4 5]
[ 9 16 25]
[18 32 50]


## Statistics

In [76]:
stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats))

1
[3 6]
21


## Reorganizing Arrays

In [79]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


#### Stacking

In [81]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.stack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

## Misc.

### Boolean Masking

In [90]:
a = np.array([[1,10,5],[2,12,30],[14,1,22]])
print(a)

print(a > 10)

print(a[a > 10])

print(np.any(a>10))

print(np.any(a>13, axis=0))

print(np.all(a>4, axis=0))

[[ 1 10  5]
 [ 2 12 30]
 [14  1 22]]
[[False False False]
 [False  True  True]
 [ True False  True]]
[12 30 14 22]
True
[ True False  True]
[False False  True]


### Index with a List

In [85]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,-1]]

array([2, 3, 9])